theme: jekyll-theme-minimal
title: Yutong Qu
logo: qyt.png
email: yutong.qu@outlook.com

description:
  Email - yutong.qu@outlook.com

github:
  repository_url: false
  is_user_page: false
  is_project_page: false
show_downloads: false

author: false
host: false

